services:
  vidhisa-api:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  vidhisa-db:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  vidhisa-dashboard:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
