/**
 * Mapping: GeoJSON English name → ISO 3166-2 code (TH-xx)
 */
const PROVINCE_CODE_MAP = {
    "Amnat Charoen": "TH-37",
    "Ang Thong": "TH-15",
    "Bangkok Metropolis": "TH-10",
    "Bueng Kan": "TH-38",
    "Buri Ram": "TH-31",
    "Chachoengsao": "TH-24",
    "Chai Nat": "TH-18",
    "Chaiyaphum": "TH-36",
    "Chanthaburi": "TH-22",
    "Chiang Mai": "TH-50",
    "Chiang Rai": "TH-57",
    "Chon Buri": "TH-20",
    "Chumphon": "TH-86",
    "Kalasin": "TH-46",
    "Kamphaeng Phet": "TH-62",
    "Kanchanaburi": "TH-71",
    "Khon Kaen": "TH-40",
    "Krabi": "TH-81",
    "Lampang": "TH-52",
    "Lamphun": "TH-51",
    "Loei": "TH-42",
    "Lop Buri": "TH-16",
    "Mae Hong Son": "TH-58",
    "Maha Sarakham": "TH-44",
    "Mukdahan": "TH-49",
    "Nakhon Nayok": "TH-26",
    "Nakhon Pathom": "TH-73",
    "Nakhon Phanom": "TH-48",
    "Nakhon Ratchasima": "TH-30",
    "Nakhon Sawan": "TH-60",
    "Nakhon Si Thammarat": "TH-80",
    "Nan": "TH-55",
    "Narathiwat": "TH-96",
    "Nong Bua Lam Phu": "TH-39",
    "Nong Khai": "TH-43",
    "Nonthaburi": "TH-12",
    "Pathum Thani": "TH-13",
    "Pattani": "TH-94",
    "Phangnga": "TH-82",
    "Phatthalung": "TH-93",
    "Phayao": "TH-56",
    "Phetchabun": "TH-67",
    "Phetchaburi": "TH-76",
    "Phichit": "TH-66",
    "Phitsanulok": "TH-65",
    "Phra Nakhon Si Ayutthaya": "TH-14",
    "Phrae": "TH-54",
    "Phuket": "TH-83",
    "Prachin Buri": "TH-25",
    "Prachuap Khiri Khan": "TH-77",
    "Ranong": "TH-85",
    "Ratchaburi": "TH-70",
    "Rayong": "TH-21",
    "Roi Et": "TH-45",
    "Sa Kaeo": "TH-27",
    "Sakon Nakhon": "TH-47",
    "Samut Prakan": "TH-11",
    "Samut Sakhon": "TH-74",
    "Samut Songkhram": "TH-75",
    "Saraburi": "TH-19",
    "Satun": "TH-91",
    "Si Sa Ket": "TH-33",
    "Sing Buri": "TH-17",
    "Songkhla": "TH-90",
    "Sukhothai": "TH-64",
    "Suphan Buri": "TH-72",
    "Surat Thani": "TH-84",
    "Surin": "TH-32",
    "Tak": "TH-63",
    "Trang": "TH-92",
    "Trat": "TH-23",
    "Ubon Ratchathani": "TH-34",
    "Udon Thani": "TH-41",
    "Uthai Thani": "TH-61",
    "Uttaradit": "TH-53",
    "Yala": "TH-95",
    "Yasothon": "TH-35",
};
