/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SyncLogsRouteImport } from './routes/sync-logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GgsRouteImport } from './routes/ggs'
import { Route as EnrollmentsRouteImport } from './routes/enrollments'
import { Route as ApproveRouteImport } from './routes/approve'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecordsIndexRouteImport } from './routes/records.index'
import { Route as ParticipantsIndexRouteImport } from './routes/participants.index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations.index'
import { Route as BranchesIndexRouteImport } from './routes/branches.index'
import { Route as RecordsNewRouteImport } from './routes/records.new'
import { Route as ParticipantsNewRouteImport } from './routes/participants.new'
import { Route as ParticipantsParticipantIdRouteImport } from './routes/participants.$participantId'
import { Route as OrganizationsNewRouteImport } from './routes/organizations.new'
import { Route as OrganizationsOrgIdRouteImport } from './routes/organizations.$orgId'
import { Route as BranchesBranchIdRouteImport } from './routes/branches.$branchId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncLogsRoute = SyncLogsRouteImport.update({
  id: '/sync-logs',
  path: '/sync-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GgsRoute = GgsRouteImport.update({
  id: '/ggs',
  path: '/ggs',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollmentsRoute = EnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproveRoute = ApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsIndexRoute = RecordsIndexRouteImport.update({
  id: '/records/',
  path: '/records/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantsIndexRoute = ParticipantsIndexRouteImport.update({
  id: '/participants/',
  path: '/participants/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesIndexRoute = BranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsNewRoute = RecordsNewRouteImport.update({
  id: '/records/new',
  path: '/records/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantsNewRoute = ParticipantsNewRouteImport.update({
  id: '/participants/new',
  path: '/participants/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantsParticipantIdRoute =
  ParticipantsParticipantIdRouteImport.update({
    id: '/participants/$participantId',
    path: '/participants/$participantId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsNewRoute = OrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrgIdRoute = OrganizationsOrgIdRouteImport.update({
  id: '/organizations/$orgId',
  path: '/organizations/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesBranchIdRoute = BranchesBranchIdRouteImport.update({
  id: '/branches/$branchId',
  path: '/branches/$branchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approve': typeof ApproveRoute
  '/enrollments': typeof EnrollmentsRoute
  '/ggs': typeof GgsRoute
  '/login': typeof LoginRoute
  '/sync-logs': typeof SyncLogsRoute
  '/users': typeof UsersRoute
  '/branches/$branchId': typeof BranchesBranchIdRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/participants/$participantId': typeof ParticipantsParticipantIdRoute
  '/participants/new': typeof ParticipantsNewRoute
  '/records/new': typeof RecordsNewRoute
  '/branches/': typeof BranchesIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/participants/': typeof ParticipantsIndexRoute
  '/records/': typeof RecordsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approve': typeof ApproveRoute
  '/enrollments': typeof EnrollmentsRoute
  '/ggs': typeof GgsRoute
  '/login': typeof LoginRoute
  '/sync-logs': typeof SyncLogsRoute
  '/users': typeof UsersRoute
  '/branches/$branchId': typeof BranchesBranchIdRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/participants/$participantId': typeof ParticipantsParticipantIdRoute
  '/participants/new': typeof ParticipantsNewRoute
  '/records/new': typeof RecordsNewRoute
  '/branches': typeof BranchesIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/participants': typeof ParticipantsIndexRoute
  '/records': typeof RecordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approve': typeof ApproveRoute
  '/enrollments': typeof EnrollmentsRoute
  '/ggs': typeof GgsRoute
  '/login': typeof LoginRoute
  '/sync-logs': typeof SyncLogsRoute
  '/users': typeof UsersRoute
  '/branches/$branchId': typeof BranchesBranchIdRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/participants/$participantId': typeof ParticipantsParticipantIdRoute
  '/participants/new': typeof ParticipantsNewRoute
  '/records/new': typeof RecordsNewRoute
  '/branches/': typeof BranchesIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/participants/': typeof ParticipantsIndexRoute
  '/records/': typeof RecordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approve'
    | '/enrollments'
    | '/ggs'
    | '/login'
    | '/sync-logs'
    | '/users'
    | '/branches/$branchId'
    | '/organizations/$orgId'
    | '/organizations/new'
    | '/participants/$participantId'
    | '/participants/new'
    | '/records/new'
    | '/branches/'
    | '/organizations/'
    | '/participants/'
    | '/records/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approve'
    | '/enrollments'
    | '/ggs'
    | '/login'
    | '/sync-logs'
    | '/users'
    | '/branches/$branchId'
    | '/organizations/$orgId'
    | '/organizations/new'
    | '/participants/$participantId'
    | '/participants/new'
    | '/records/new'
    | '/branches'
    | '/organizations'
    | '/participants'
    | '/records'
  id:
    | '__root__'
    | '/'
    | '/approve'
    | '/enrollments'
    | '/ggs'
    | '/login'
    | '/sync-logs'
    | '/users'
    | '/branches/$branchId'
    | '/organizations/$orgId'
    | '/organizations/new'
    | '/participants/$participantId'
    | '/participants/new'
    | '/records/new'
    | '/branches/'
    | '/organizations/'
    | '/participants/'
    | '/records/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApproveRoute: typeof ApproveRoute
  EnrollmentsRoute: typeof EnrollmentsRoute
  GgsRoute: typeof GgsRoute
  LoginRoute: typeof LoginRoute
  SyncLogsRoute: typeof SyncLogsRoute
  UsersRoute: typeof UsersRoute
  BranchesBranchIdRoute: typeof BranchesBranchIdRoute
  OrganizationsOrgIdRoute: typeof OrganizationsOrgIdRoute
  OrganizationsNewRoute: typeof OrganizationsNewRoute
  ParticipantsParticipantIdRoute: typeof ParticipantsParticipantIdRoute
  ParticipantsNewRoute: typeof ParticipantsNewRoute
  RecordsNewRoute: typeof RecordsNewRoute
  BranchesIndexRoute: typeof BranchesIndexRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  ParticipantsIndexRoute: typeof ParticipantsIndexRoute
  RecordsIndexRoute: typeof RecordsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync-logs': {
      id: '/sync-logs'
      path: '/sync-logs'
      fullPath: '/sync-logs'
      preLoaderRoute: typeof SyncLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ggs': {
      id: '/ggs'
      path: '/ggs'
      fullPath: '/ggs'
      preLoaderRoute: typeof GgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollments': {
      id: '/enrollments'
      path: '/enrollments'
      fullPath: '/enrollments'
      preLoaderRoute: typeof EnrollmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approve': {
      id: '/approve'
      path: '/approve'
      fullPath: '/approve'
      preLoaderRoute: typeof ApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/': {
      id: '/records/'
      path: '/records'
      fullPath: '/records/'
      preLoaderRoute: typeof RecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participants/': {
      id: '/participants/'
      path: '/participants'
      fullPath: '/participants/'
      preLoaderRoute: typeof ParticipantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/': {
      id: '/branches/'
      path: '/branches'
      fullPath: '/branches/'
      preLoaderRoute: typeof BranchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/new': {
      id: '/records/new'
      path: '/records/new'
      fullPath: '/records/new'
      preLoaderRoute: typeof RecordsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participants/new': {
      id: '/participants/new'
      path: '/participants/new'
      fullPath: '/participants/new'
      preLoaderRoute: typeof ParticipantsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participants/$participantId': {
      id: '/participants/$participantId'
      path: '/participants/$participantId'
      fullPath: '/participants/$participantId'
      preLoaderRoute: typeof ParticipantsParticipantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/new': {
      id: '/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof OrganizationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$orgId': {
      id: '/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof OrganizationsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/$branchId': {
      id: '/branches/$branchId'
      path: '/branches/$branchId'
      fullPath: '/branches/$branchId'
      preLoaderRoute: typeof BranchesBranchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApproveRoute: ApproveRoute,
  EnrollmentsRoute: EnrollmentsRoute,
  GgsRoute: GgsRoute,
  LoginRoute: LoginRoute,
  SyncLogsRoute: SyncLogsRoute,
  UsersRoute: UsersRoute,
  BranchesBranchIdRoute: BranchesBranchIdRoute,
  OrganizationsOrgIdRoute: OrganizationsOrgIdRoute,
  OrganizationsNewRoute: OrganizationsNewRoute,
  ParticipantsParticipantIdRoute: ParticipantsParticipantIdRoute,
  ParticipantsNewRoute: ParticipantsNewRoute,
  RecordsNewRoute: RecordsNewRoute,
  BranchesIndexRoute: BranchesIndexRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  ParticipantsIndexRoute: ParticipantsIndexRoute,
  RecordsIndexRoute: RecordsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
