/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrKeyRouteImport } from './routes/br.$key'
import { Route as BrKeySearchRouteImport } from './routes/br.$key.search'
import { Route as BrKeyMeParticipantIdRouteImport } from './routes/br.$key.me.$participantId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrKeyRoute = BrKeyRouteImport.update({
  id: '/br/$key',
  path: '/br/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const BrKeySearchRoute = BrKeySearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => BrKeyRoute,
} as any)
const BrKeyMeParticipantIdRoute = BrKeyMeParticipantIdRouteImport.update({
  id: '/me/$participantId',
  path: '/me/$participantId',
  getParentRoute: () => BrKeyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/br/$key': typeof BrKeyRouteWithChildren
  '/br/$key/search': typeof BrKeySearchRoute
  '/br/$key/me/$participantId': typeof BrKeyMeParticipantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/br/$key': typeof BrKeyRouteWithChildren
  '/br/$key/search': typeof BrKeySearchRoute
  '/br/$key/me/$participantId': typeof BrKeyMeParticipantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/br/$key': typeof BrKeyRouteWithChildren
  '/br/$key/search': typeof BrKeySearchRoute
  '/br/$key/me/$participantId': typeof BrKeyMeParticipantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/br/$key' | '/br/$key/search' | '/br/$key/me/$participantId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/br/$key' | '/br/$key/search' | '/br/$key/me/$participantId'
  id:
    | '__root__'
    | '/'
    | '/br/$key'
    | '/br/$key/search'
    | '/br/$key/me/$participantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrKeyRoute: typeof BrKeyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/br/$key': {
      id: '/br/$key'
      path: '/br/$key'
      fullPath: '/br/$key'
      preLoaderRoute: typeof BrKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/br/$key/search': {
      id: '/br/$key/search'
      path: '/search'
      fullPath: '/br/$key/search'
      preLoaderRoute: typeof BrKeySearchRouteImport
      parentRoute: typeof BrKeyRoute
    }
    '/br/$key/me/$participantId': {
      id: '/br/$key/me/$participantId'
      path: '/me/$participantId'
      fullPath: '/br/$key/me/$participantId'
      preLoaderRoute: typeof BrKeyMeParticipantIdRouteImport
      parentRoute: typeof BrKeyRoute
    }
  }
}

interface BrKeyRouteChildren {
  BrKeySearchRoute: typeof BrKeySearchRoute
  BrKeyMeParticipantIdRoute: typeof BrKeyMeParticipantIdRoute
}

const BrKeyRouteChildren: BrKeyRouteChildren = {
  BrKeySearchRoute: BrKeySearchRoute,
  BrKeyMeParticipantIdRoute: BrKeyMeParticipantIdRoute,
}

const BrKeyRouteWithChildren = BrKeyRoute._addFileChildren(BrKeyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrKeyRoute: BrKeyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
