/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrKeyIndexRouteImport } from './routes/br.$key.index'
import { Route as BrKeySearchRouteImport } from './routes/br.$key.search'
import { Route as BrKeyMeParticipantIdRouteImport } from './routes/br.$key.me.$participantId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrKeyIndexRoute = BrKeyIndexRouteImport.update({
  id: '/br/$key/',
  path: '/br/$key/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrKeySearchRoute = BrKeySearchRouteImport.update({
  id: '/br/$key/search',
  path: '/br/$key/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BrKeyMeParticipantIdRoute = BrKeyMeParticipantIdRouteImport.update({
  id: '/br/$key/me/$participantId',
  path: '/br/$key/me/$participantId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/br/$key/search': typeof BrKeySearchRoute
  '/br/$key/': typeof BrKeyIndexRoute
  '/br/$key/me/$participantId': typeof BrKeyMeParticipantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/br/$key/search': typeof BrKeySearchRoute
  '/br/$key': typeof BrKeyIndexRoute
  '/br/$key/me/$participantId': typeof BrKeyMeParticipantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/br/$key/search': typeof BrKeySearchRoute
  '/br/$key/': typeof BrKeyIndexRoute
  '/br/$key/me/$participantId': typeof BrKeyMeParticipantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/br/$key/search'
    | '/br/$key/'
    | '/br/$key/me/$participantId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/br/$key/search' | '/br/$key' | '/br/$key/me/$participantId'
  id:
    | '__root__'
    | '/'
    | '/br/$key/search'
    | '/br/$key/'
    | '/br/$key/me/$participantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrKeySearchRoute: typeof BrKeySearchRoute
  BrKeyIndexRoute: typeof BrKeyIndexRoute
  BrKeyMeParticipantIdRoute: typeof BrKeyMeParticipantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/br/$key/': {
      id: '/br/$key/'
      path: '/br/$key'
      fullPath: '/br/$key/'
      preLoaderRoute: typeof BrKeyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/br/$key/search': {
      id: '/br/$key/search'
      path: '/br/$key/search'
      fullPath: '/br/$key/search'
      preLoaderRoute: typeof BrKeySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/br/$key/me/$participantId': {
      id: '/br/$key/me/$participantId'
      path: '/br/$key/me/$participantId'
      fullPath: '/br/$key/me/$participantId'
      preLoaderRoute: typeof BrKeyMeParticipantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrKeySearchRoute: BrKeySearchRoute,
  BrKeyIndexRoute: BrKeyIndexRoute,
  BrKeyMeParticipantIdRoute: BrKeyMeParticipantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
